[package]
edition = "2021"
name = "aunisoma"
version = "0.1.0"
authors = ["Walter Smith <walter@wrsmap.com>"]
resolver = "2"

[dependencies]
panic-halt = "1.0.0"

embedded-hal = "1.0.0"
embedded-hal-async = "1.0.0"
embedded-io = "0.6.1"
embedded-io-async = "0.6.1"
embedded-storage = "0.3.1"

embassy-executor = { path = "../embassy/embassy-executor", features = [
    "task-arena-size-1024",
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
] }
embassy-stm32 = { path = "../embassy/embassy-stm32", features = [
    "stm32f103c8",
    "unstable-pac",
    "memory-x",
    "time-driver-any",
] }
embassy-sync = { path = "../embassy/embassy-sync" }
embassy-time = { path = "../embassy/embassy-time" }

cortex-m = { version = "0.7.6", features = ["critical-section-single-core"] }
cortex-m-rt = "0.7.3"
heapless = "0.8.0"
static_cell = "2.1.0"

[profile.dev]
opt-level = 3
lto = true

[profile.release]
codegen-units = 1 # better optimizations
debug = true      # symbols are nice and they don't increase the size on Flash
lto = true        # better optimizations
