#!/usr/bin/env python3

import os
import subprocess
import sys

# Extract serials from stlink_info lines like
#   serial:     0668FF485370514867131336
stlink_info = subprocess.run(["st-info", "--probe"], capture_output=True, text=True).stdout.splitlines()
serials = [line.split(":")[1].strip() for line in stlink_info if line.strip().startswith("serial:")]

suffix = sys.argv[1]

# find serial by suffix
serial = [serial for serial in serials if serial.endswith(suffix)]
if len(serial) == 0:
    print(f"Error: no serial found for suffix {suffix}", file=sys.stderr)
    sys.exit(1)
if len(serial) > 1:
    print(f"Error: suffix {suffix} is not unique", file=sys.stderr)
    sys.exit(1)

serial = serial[0]

print(f"Using device serial {serial}")

with open("select-serial.cfg", "w") as cfg_file:
    cfg_file.write(f"puts \"Using device serial {serial}\"\n")
    cfg_file.write(f"adapter serial {serial}\n")
