[target.'cfg(all(target_arch = "arm", target_os = "none"))']
# runner = "probe-rs run --chip STM32F103C8"
runner = "arm-none-eabi-gdb -q -x openocd.gdb"
rustflags = [
  "-C", "link-arg=-Tdefmt.x",
  "-C", "link-args=-Map=target/app.map"
]

[build]
target = "thumbv7m-none-eabi"

[env]
DEFMT_LOG = "aunisoma=debug,embassy_usb=warn"
# DEFMT_LOG = "info"

# Link scripts are set in build.rs
[unstable]
build-std = ["core", "alloc"]
build-std-features = ["panic_immediate_abort"]
